import ShyForm from './src/ShyForm'
export * from './src/types/form'
export * from './src/types/formItem'
export * from './src/types/index'
export * from './src/ShyComponentMap'
export type { FormSchema as ShyFormSchema } from './src/types/form'
export { useComponentRegister as useShyComponentRegister } from './src/hooks/useComponentRegister'
export { useShyForm, useShyForm as useForm } from './src/hooks/useShyForm'
export { default as ShyFormItem } from './src/components/FormItem'
export { default as ShyApiSelect } from './src/components/ApiSelect.vue'
export { default as ShyRadioButtonGroup } from './src/components/RadioButtonGroup.vue'
export { default as ShyApiTreeSelect } from './src/components/ApiTreeSelect.vue'
export { default as ShyApiTree } from './src/components/ApiTree.vue'
export { default as ShyApiRadioGroup } from './src/components/ApiRadioGroup.vue'
export { default as ShyApiCascader } from './src/components/ApiCascader.vue'
export { default as ShyApiTransfer } from './src/components/ApiTransfer.vue'
export { ShyFormTable as ShyTableChildren } from './src/components/Table'
export { default as ShyApiModalSelect } from './src/components/ApiModalSelect/ApiModalSelect.vue'
export { default as ShyFormWrapper } from './src/components/FormWrapper.vue'

export { ShyForm, ShyForm as BasicForm }
