import 'virtual:windi-base.css'
import 'virtual:windi-components.css'
import 'virtual:windi-utilities.css'
import 'ant-design-vue/dist/reset.css'

export * from './src/Form'
export * from './src/Container'
export * from './src/Table'
export * from './src/Modal'
export * from './src/Page'
export * from './src/Description'
export * from './src/Scrollbar'
// export * from './src/FlowChart'
export * from './src/Dropdown'
export * from './src/Drawer'
export * from './src/Cropper'
export * from './src/CountTo'
export * from './src/CountDown'
export * from './src/Container'
export * from './src/ClickOutSide'
// export * from './src/DictTag'
export * from './src/Button'
export * from './src/Basic'
export * from './src/Tree'
export * from './src/Icon'
export * from './src/Loading'
export * from './src/StrengthMeter'
export * from './src/TablePlus'
export * from './src/AdvancedSearch'
export * from './src/Label'
export * from './src/BasicContainer'
export * from './src/DescriptionsForm'
export * from './src/BasicResizeWrapper'
export * from './src/ColorPickerPopover'
export * from './src/ShyTable'

import { registerGlobalConfig } from './config/index'

export { registerGlobalConfig }
